### Theme config
name = "plastic love"
description = "When city pop is not enough, this theme is for you"
license = "BSD-2-Clause"

[author]
name = "Zhengyan Peh (zypeh)"
homepage = "https://zypeh.github.io"
